### ISSUE TITLE
Profile menu Github

### ISSUE THREAD

**Issue by Katuva** [liorgrossman/darkness#46]
The profile dropdown menu in github is a bit wonky.

I've looked at the css, but can't seem to find the issue. Here are some screenshots for reference.

When the menu is first opened:

![chrome_2017-04-14_23-21-58](https://cloud.githubusercontent.com/assets/3183511/25057640/93a873b4-2169-11e7-8018-0d67e4b93ae4.png)

And then when hovered over:

![chrome_2017-04-14_23-23-10](https://cloud.githubusercontent.com/assets/3183511/25057651/a023dfca-2169-11e7-8b9f-bcf7309a526c.png)

**Comment by theme1256** [comment]
I had a quick look and it looks like it's not a problem in the `material` theme, perhaps due to some of the colors being the same in that theme.

I think the source of the problem might be the following selector
```css
.js-menu-content div:hover, 
.js-menu-content .select-menu-list > div > a:hover, 
.js-menu-content .select-menu-list > a:hover {
    background-color: #d7d6d5 !important;
}
```
Primarily the `.js-menu-content div:hover` part.

Hope this helps you find a solution 😄
